FLASK_APP="app"
FLASK_DEBUG=False
FLASK_RUN_HOST="0.0.0.0"
FLASK_RUN_PORT=5000

FLASK_K8S_ANNOTATION_PREFIX="kubeboard.xyz"

FLASK_APP_TITLE="KubeBoard"
FLASK_APP_DEFAULT_ICON="fa-external-link"  # See https://forkaweso.me/Fork-Awesome/icons/
FLASK_APP_HIDE_BY_DEFAULT="false"

FLASK_THEME_PRIMARY_COLOR="#0075ff"
FLASK_THEME_SECONDARY_COLOR="#AABBC3"
FLASK_THEME_BACKGROUND_URL="../img/earth-background.jpg"
